---
apiVersion: networkaddonsoperator.network.kubevirt.io/v1
kind: NetworkAddonsConfig
metadata:
  name: cluster
spec:
  imagePullPolicy: IfNotPresent
  kubeMacPool: {}
  linuxBridge: {}
  macvtap: {}
  multus: {}
  nmstate: {}
  ovs: {}
