apiVersion: v1beta3
baseDomain: tt.testing
compute:
- name: worker
  platform: {}
  replicas: 1
controlPlane:
  name: master
  platform: {}
  replicas: 1
metadata:
  name: test-1
networking:
  clusterNetworks:
  - cidr: 10.128.0.0/14
    hostSubnetLength: 9
  machineCIDR: 192.168.126.0/24
  serviceCIDR: 172.30.0.0/16
  type: OpenShiftSDN
platform:
  libvirt:
    URI: qemu+tcp://192.168.122.1/system
    network:
      if: tt0
